name: PR Check

on:
  pull_request:
    branches: [ main ]

jobs:
  container-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run tests
        run: make test
      - name: Build binaries
        run: make build
      - name: Build container
        run: make image
